name: Check WP plugin updates
on:
  schedule: [{ cron: "0 6 * * 1" }]
  workflow_dispatch: {}
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq curl
      - name: Bump plugins.lock
        run: |
          set -e
          TMP=plugins.lock.new
          > "$TMP"
          while IFS= read -r line; do
            [ -z "$line" ] && continue
            slug="${line%@*}"; cur="${line#*@}"
            latest=$(curl -fsS "https://api.wordpress.org/plugins/info/1.2/?action=plugin_information&request[slug]=$slug" | jq -r '.version')
            [ -n "$latest" ] || { echo "No version for $slug"; exit 1; }
            if [ "$latest" != "$cur" ]; then
              echo "$slug@$latest" >> "$TMP"
            else
              echo "$line" >> "$TMP"
            fi
          done < plugins.lock
          if ! cmp -s plugins.lock "$TMP"; then mv "$TMP" plugins.lock; else exit 0; fi
      - uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(wp): bump plugins.lock"
          title: "Bump WordPress plugins"
          body: "Actualiza versiones de plugins."
          branch: chore/bump-wp-plugins
